 # Copyright (c) 2022, salesforce.com, inc.
 # All rights reserved.
 # SPDX-License-Identifier: BSD-3-Clause
 # For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause

datasets:
  mnli:
    # data_dir: ${env.data_dir}/datasets
    data_type: images # [images|videos|features]

    build_info:
      # Be careful not to append minus sign (-) before split to avoid itemizing
      annotations:
        txt_train:
          url: ~/LAVIS/cache/GLUE/MNLI/train.tsv
          storage: GLUE/MNLI/train.json
        val:
          url: ~/LAVIS/cache/GLUE/MNLI/train.tsv
          storage: GLUE/MNLI/dev.json
        test:
          url: ~/LAVIS/cache/GLUE/MNLI/train.tsv
          storage: GLUE/MNLI/dev.json
      images:
          storage: GLUE/MNLI/dev.json
          # storage: /export/share/datasets/vision/flickr30k/flickr30k-images
