 # Copyright (c) 2022, salesforce.com, inc.
 # All rights reserved.
 # SPDX-License-Identifier: BSD-3-Clause
 # For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause

model:
  arch: vilt_distill

  load_pretrained: True
  pretrained: "https://storage.googleapis.com/sfr-pcl-data-research/ALBEF/ALBEF.pth"

  # bert config

  mlm_mask_prob: 0.15

  embed_dim: 256
  momentum: 0.995
  alpha: 0.4
  temp: 0.07

  max_txt_len: 30

preprocess:
    vis_processor:
        train:
          name: "vilt_image_train"
          image_size: 256
    text_processor:
        train:
          name: "blip_caption"
